name: Flutter Build Android APK (Manual)

on:
  workflow_dispatch:  # Solo se ejecuta manualmente desde la pestaña Actions

jobs:
  build-android:
    runs-on: ubuntu-latest # Usamos Ubuntu porque es más rápido para compilar Android

    steps:
      - name: Checkout código
        uses: actions/checkout@v5

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17' # Requerido por las versiones recientes de Android y Gradle

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # Cambia a 'beta' si lo necesitas

      - name: Obtener dependencias
        run: flutter pub get

      - name: actualizar depencencias
        run: flutter pub upgrade

      - name: Actualizar Gradle Wrapper
        run: |
          cd android
          sed -i 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-9.1.0-all.zip|' gradle/wrapper/gradle-wrapper.properties
          cat gradle/wrapper/gradle-wrapper.properties

      - name: Actualizar versión de AGP
        run: |
          cd android
          sed -i -E 's|(id\("com\.android\.application"\) version ")[^"]+(")|\19.0.1\2|' settings.gradle.kts
          cat settings.gradle.kts

      - name: Actualizar versión de Kotlin
        run: |
          cd android
          sed -i -E 's|(id\("org\.jetbrains\.kotlin\.android"\) version ")[^"]+(")|\12.2.20\2|' settings.gradle.kts
          cat settings.gradle.kts

      - name: Opt-out de android.newDsl (compatibilidad con Flutter Gradle plugin)
        run: |
          cd android
          echo "android.newDsl=false" >> gradle.properties
          cat gradle.properties

      - name: Compilar APK para Android
        run: flutter build apk --release

      - name: Subir artifact APK
        uses: actions/upload-artifact@v5
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 1
